#!/bin/sh

usage() {
    echo "usage:$0 [deploydb|deploy|xml-java-schema|premium|sdk]"
}

sdk() {
    set -u
    cd sdk/src/main/java/org/zstack/sdk/
    find . -type f  | grep -E -v "(ZSClient|ZSConfig|ApiException|AsyncRestState|Completion|Constants|ErrorCode|ErrorCodeList|InternalCompletion|ApiResult|Param|RestInfo|AbstractAction|QueryAction).java" | xargs rm -f
    cd -
    rm -rf ~/zstack-sdk/java
    cd test
    mvn test -Dtest=TestGenerateSDK
    cd - > /dev/null
    yes | cp ~/zstack-sdk/java/* sdk/src/main/java/org/zstack/sdk/
    set +u
}

run_profile() {
    if test x$1 = x'premium'; then
        mvn -Dmaven.test.skip=true -P premium clean install
    elif test x$1 = x'sdk'; then
        sdk
    else
        mvn -pl build -P $1 exec:exec -D$1
    fi
}

if [ "$#" -eq 0 ]; then
    usage
    exit 1
fi

for cmd in $@
do
    run_profile ${cmd}
done
